/* 
 * This file is part of linllt.
 * All Rights Reserved.
 * 
 * Copyright (C) Micro-Epsilon Messtechnik GmbH & Co. KG
 *
 * THIS SOURCE FILE IS THE PROPERTY OF MICRO-EPSILON MESSTECHNIK AND
 * IS NOT TO BE RE-DISTRIBUTED BY ANY MEANS WHATSOEVER WITHOUT THE
 * EXPRESSED WRITTEN CONSENT OF MICRO-EPSILON MESSTECHNIK.
 *
 * Author: Daniel Rauch <daniel.rauch@micro-epsilon.de>
 *
 */

/***
 MACROS
***/

#ifndef LLTDATATYPES_H
#define LLTDATATYPES_H

#define __STDC_FORMAT_MACROS

#ifdef UNUSED
#elif defined(__GNUC__)
#define UNUSED(x) UNUSED_##x __attribute__((unused))
#elif defined(__LCLINT__)
#define UNUSED(x) /*@unused@*/ x
#else
#define UNUSED(x) x
#endif

#define WAIT_OBJECT_0 0

// status and control register
#define FEATURE_FUNCTION_SERIAL 0xf0000410
#define FEATURE_FUNCTION_PEAKFILTER_WIDTH 0xf0b02000
#define FEATURE_FUNCTION_PEAKFILTER_HEIGHT 0xf0b02004
#define FEATURE_FUNCTION_FREE_MEASURINGFIELD_Z 0xf0b02008
#define FEATURE_FUNCTION_FREE_MEASURINGFIELD_X 0xf0b0200c
#define FEATURE_FUNCTION_DYNAMIC_TRACK_DIVISOR 0xf0b02010
#define FEATURE_FUNCTION_DYNAMIC_TRACK_FACTOR 0xf0b02014
#define FEATURE_FUNCTION_CALIBRATION_0 0xf0b02020
#define FEATURE_FUNCTION_CALIBRATION_1 0xf0b02024
#define FEATURE_FUNCTION_CALIBRATION_2 0xf0b02028
#define FEATURE_FUNCTION_CALIBRATION_3 0xf0b0202c
#define FEATURE_FUNCTION_CALIBRATION_4 0xf0b02030
#define FEATURE_FUNCTION_CALIBRATION_5 0xf0b02034
#define FEATURE_FUNCTION_CALIBRATION_6 0xf0b02038
#define FEATURE_FUNCTION_CALIBRATION_7 0xf0b0203c
#define FEATURE_FUNCTION_LASERPOWER 0xf0f00824
#define FEATURE_FUNCTION_MEASURINGFIELD 0xf0f00880
#define FEATURE_FUNCTION_TRIGGER 0xf0f00830
#define FEATURE_FUNCTION_SHUTTERTIME 0xf0f0081c
#define FEATURE_FUNCTION_IDLETIME 0xf0f00800
#define FEATURE_FUNCTION_PROCESSING_PROFILEDATA 0xf0f00804
#define FEATURE_FUNCTION_THRESHOLD 0xf0f00810
#define FEATURE_FUNCTION_MAINTENANCEFUNCTIONS 0xf0f0088c
#define FEATURE_FUNCTION_REARRANGEMENT_PROFILE 0xf0f0080c
#define FEATURE_FUNCTION_PROFILE_FILTER 0xf0f00818
#define FEATURE_FUNCTION_RS422_INTERFACE_FUNCTION 0xf0f008c0
#define FEATURE_FUNCTION_PACKET_DELAY 0x00000d08
#define FEATURE_FUNCTION_SHARPNESS 0xf0f00808
#define FEATURE_FUNCTION_TEMPERATURE 0xf0f0082c
#define FEATURE_FUNCTION_SATURATION 0xf0f00814
#define FEATURE_FUNCTION_CAPTURE_QUALITY 0xf0f008c4

// inquiry Register
#define INQUIRY_FUNCTION_LASERPOWER 0xf0f00524
#define INQUIRY_FUNCTION_MEASURINGFIELD 0xf0f00580
#define INQUIRY_FUNCTION_TRIGGER 0xf0f00530
#define INQUIRY_FUNCTION_SHUTTERTIME 0xf0f0051c
#define INQUIRY_FUNCTION_IDLETIME 0xf0f00500
#define INQUIRY_FUNCTION_PROCESSING_PROFILEDATA 0xf0f00504
#define INQUIRY_FUNCTION_THRESHOLD 0xf0f00510
#define INQUIRY_FUNCTION_MAINTENANCEFUNCTIONS 0xf0f0058c
#define INQUIRY_FUNCTION_REARRANGEMENT_PROFILE 0xf0f0050c
#define INQUIRY_FUNCTION_PROFILE_FILTER 0xf0f00518
#define INQUIRY_FUNCTION_RS422_INTERFACE_FUNCTION 0xf0f005c0
#define INQUIRY_FUNCTION_SHARPNESS 0xf0f00508
#define INQUIRY_FUNCTION_TEMPERATURE 0xf0f0052c
#define INQUIRY_FUNCTION_SATURATION 0xf0f00514
#define INQUIRY_FUNCTION_CAPTURE_QUALITY 0xf0f005c4

// processing flags
#define PROC_HIGH_RESOLUTION 1
#define PROC_CALIBRATION (1 << 1)
#define PROC_MULTIREFL_ALL (0 << 2)
#define PROC_MULITREFL_FIRST (1 << 2)
#define PROC_MULITREFL_LAST (2 << 2)
#define PROC_MULITREFL_LARGESTAREA (3 << 2)
#define PROC_MULITREFL_MAXINTENS (4 << 2)
#define PROC_MULITREFL_SINGLE (5 << 2)
#define PROC_POSTPROCESSING_ON (1 << 5)
#define PROC_FLIP_DISTANCE (1 << 6)
#define PROC_FLIP_POSITION (1 << 7)
#define PROC_AUTOSHUTTER_DELAY (1 << 8)
#define PROC_SHUTTERALIGN_CENTRE (0 << 9)
#define PROC_SHUTTERALIGN_RIGHT (1 << 9)
#define PROC_SHUTTERALIGN_LEFT (2 << 9)
#define PROC_SHUTTERALIGN_OFF (3 << 9)
#define PROC_AUTOSHUTTER_ADVANCED (1 << 11)

// threshold flags
#define THRESHOLD_DYNAMIC (1 << 24)
#define THRESHOLD_VIDEO_FILTER (1 << 11)
#define THRESHOLD_BACKGROUND_FILTER (1 << 10)

// shutter flags
#define SHUTTER_AUTOMATIC (1 << 24)

// laser power flags
#define LASER_OFF 0
#define LASER_REDUCED_POWER 1
#define LASER_FULL_POWER 2
#define LASER_PULSMODE (1 << 11)

// temperature register
#define TEMP_PREPARE_VALUE 0x86000000

// trigger flags
#define TRIG_MODE_EDGE (0 << 16)
#define TRIG_MODE_PULSE (1 << 16)
#define TRIG_MODE_GATE (2 << 16)
#define TRIG_MODE_ENCODER (3 << 16)
#define TRIG_INPUT_RS422 (0 << 21)
#define TRIG_INPUT_DIGIN (1 << 21)
#define TRIG_POLARITY_LOW (0 << 24)
#define TRIG_POLARITY_HIGH (1 << 24)
#define TRIG_EXT_ACTIVE (1 << 25)
#define TRIG_INTERNAL (0 << 25)

// measuring field flags
#define MEASFIELD_ACTIVATE_FREE (1 << 11)

// maintenance flags
#define MAINTENANCE_LOOPBACK (1 << 1)
#define MAINTENANCE_ENCODER_ACTIVE (1 << 3)
#define MAINTENANCE_SUPPRESS_REGISTER_RESET (1 << 5)
#define MAINTENANCE_UM_LOAD_VIA_DIGIN (0 << 6)
#define MAINTENANCE_UM_SUPPRESS_UNTIL_REBOOT (1 << 6)
#define MAINTENANCE_UM_SUPPRESS_UNTIL_GVCP_CLOSE (2 << 6)
#define MAINTENANCE_UM_SUPPRESS_UNTIL_REBOOT_GVCP_CLOSE (3 << 6)

// multiport flags
#define MULTI_LEVEL_5V (0 << 11)
#define MULTI_LEVEL_24V (1 << 11)
#define MULTI_RS422_TERM_ON (0 << 10)
#define MULTI_RS422_TERM_OFF (1 << 10)
#define MULTI_ENCODER_BIDIRECT (0 << 9)
#define MULTI_ENCODER_UNIDIRECT (1 << 9)
#define MULTI_DIGIN_ENC_INDEX (0 << 4)
#define MULTI_DIGIN_ENC_TRIG (1 << 4)
#define MULTI_DIGIN_TRIG_ONLY (2 << 4)
#define MULTI_DIGIN_TRIG_UM (3 << 4)
#define MULTI_DIGIN_UM (4 << 4)
#define MULTI_DIGIN_TS (5 << 4)
#define MULTI_DIGIN_FRAMETRIG_BI (6 << 4)
#define MULTI_DIGIN_FRAMETRIG_UNI (7 << 4)
#define MULTI_DIGIN_GATED_ENCODER (8 << 4)
#define MULTI_RS422_115200 0
#define MULTI_RS422_57600 1
#define MULTI_RS422_38400 2
#define MULTI_RS422_19200 3
#define MULTI_RS422_9600 4
#define MULTI_RS422_TRIG_IN 5
#define MULTI_RS422_TRIG_OUT 6
#define MULTI_RS422_CMM 7

#define RS422_INTERFACE_FUNCTION_AUTO_27xx 0
#define RS422_INTERFACE_FUNCTION_SERIALPORT_115200_27xx 1
#define RS422_INTERFACE_FUNCTION_TRIGGER_27xx 2
#define RS422_INTERFACE_FUNCTION_CMM_TRIGGER_27xx 3
#define RS422_INTERFACE_FUNCTION_ENCODER_27xx 4
#define RS422_INTERFACE_FUNCTION_DIGITAL_OUTPUT_27xx 6
#define RS422_INTERFACE_FUNCTION_TRIGGER_LASER_PULSE_27xx 7
#define RS422_INTERFACE_FUNCTION_SERIALPORT_57600_27xx 8
#define RS422_INTERFACE_FUNCTION_SERIALPORT_38400_27xx 9
#define RS422_INTERFACE_FUNCTION_SERIALPORT_19200_27xx 10
#define RS422_INTERFACE_FUNCTION_SERIALPORT_9600_27xx 11

// profile filter flags
#define FILTER_RESAMPLE_EXTRAPOLATE_POINTS (1 << 11)
#define FILTER_RESAMPLE_ALL_INFO (1 << 10)
#define FILTER_RESAMPLE_DISABLED (0 << 4)
#define FILTER_RESAMPLE_TINY (1 << 4)
#define FILTER_RESAMPLE_VERYSMALL (2 << 4)
#define FILTER_RESAMPLE_SMALL (3 << 4)
#define FILTER_RESAMPLE_MEDIUM (4 << 4)
#define FILTER_RESAMPLE_LARGE (5 << 4)
#define FILTER_RESAMPLE_VERYLARGE (6 << 4)
#define FILTER_RESAMPLE_HUGE (7 << 4)
#define FILTER_MEDIAN_DISABLED (0 << 2)
#define FILTER_MEDIAN_3 (1 << 2)
#define FILTER_MEDIAN_5 (2 << 2)
#define FILTER_MEDIAN_7 (3 << 2)
#define FILTER_AVG_DISABLED 0
#define FILTER_AVG_3 1
#define FILTER_AVG_5 2
#define FILTER_AVG_7 3

// container flags
#define CONTAINER_STRIPE_4 (1 << 23)
#define CONTAINER_STRIPE_3 (1 << 22)
#define CONTAINER_STRIPE_2 (1 << 21)
#define CONTAINER_STRIPE_1 (1 << 20)
#define CONTAINER_JOIN (1 << 19)
#define CONTAINER_DATA_SIGNED (1 << 18)
#define CONTAINER_DATA_LSBF (1 << 17)
#define CONTAINER_DATA_TS (1 << 11)
#define CONTAINER_DATA_EMPTYFIELD4TS (1 << 10)
#define CONTAINER_DATA_LOOPBACK (1 << 9)
#define CONTAINER_DATA_MOM0U (1 << 8)
#define CONTAINER_DATA_MOM0L (1 << 7)
#define CONTAINER_DATA_MOM1U (1 << 6)
#define CONTAINER_DATA_MOM1L (1 << 5)
#define CONTAINER_DATA_WIDTH (1 << 4)
#define CONTAINER_DATA_INTENS (1 << 3)
#define CONTAINER_DATA_THRES (1 << 2)
#define CONTAINER_DATA_X (1 << 1)
#define CONTAINER_DATA_Z (1 << 0)

// return values for profile conversion
#define CONVERT_X 0x00000800
#define CONVERT_Z 0x00001000
#define CONVERT_WIDTH 0x00000100
#define CONVERT_MAXIMUM 0x00000200
#define CONVERT_THRESHOLD 0x00000400
#define CONVERT_M0 0x00002000
#define CONVERT_M1 0x00004000

// general return values
#define GENERAL_FUNCTION_DEVICE_NAME_NOT_SUPPORTED 4
#define GENERAL_FUNCTION_OK 1
#define GENERAL_FUNCTION_NOT_AVAILABLE 0

// specific return values
#define ERROR_GETDEVICENAME_SIZE_TOO_LOW -1
#define ERROR_GETDEVICENAME_NO_BUFFER -2

#define ERROR_PROFTRANS_NO_NEW_PROFILE -104
#define ERROR_PROFTRANS_BUFFER_SIZE_TOO_LOW -105
#define ERROR_PROFTRANS_NO_PROFILE_TRANSFER -106
#define ERROR_PROFTRANS_REFLECTION_NUMBER_TOO_HIGH -110
#define ERROR_PROFTRANS_WRONG_BUFFER_POINTER -113
#define ERROR_PROFTRANS_WRONG_TRANSFER_CONFIG -114
#define ERROR_PROFTRANS_LOOPBACK_NOT_SUPPORTED -115
#define ERROR_PROFTRANS_WRONG_DATA_SIZE -116
#define ERROR_PROFTRANS_WRONG_DATA_FORMAT -117
#define ERROR_PROFTRANS_WRONG_RESOLUTION -118
#define ERROR_PROFTRANS_REFLECTION_NO_DATA -119

#define ERROR_SETGETFUNCTIONS_WRONG_BUFFER_COUNT -150
#define ERROR_SETGETFUNCTIONS_PACKET_SIZE -151
#define ERROR_SETGETFUNCTIONS_WRONG_PROFILE_CONFIG -152
#define ERROR_SETGETFUNCTIONS_NOT_SUPPORTED_RESOLUTION -153
#define ERROR_SETGETFUNCTIONS_REFLECTION_NUMBER_TOO_HIGH -154
#define ERROR_SETGETFUNCTIONS_WRONG_FEATURE_ADRESS -155
#define ERROR_SETGETFUNCTIONS_SIZE_TOO_LOW -156
#define ERROR_SETGETFUNCTIONS_WRONG_PROFILE_SIZE -157
#define ERROR_SETGETFUNCTIONS_MOD_4 -158
#define ERROR_SETGETFUNCTIONS_REARRANGEMENT_PROFILE -159
#define ERROR_SETGETFUNCTIONS_USER_MODE_TOO_HIGH -160
#define ERROR_SETGETFUNCITONS_USER_MODE_FACTORY_DEFAULT -161
#define ERROR_SETGETFUNCITONS_HEARTBEAT_TOO_HIGH -162

#define ERROR_GETDEVINTERFACE_REQUEST_COUNT -251
#define ERROR_GETDEVINTERFACE_INTERNAL -253

#define ERROR_CONNECT_LLT_COUNT -300
#define ERROR_CONNECT_SELECTED_LLT -301
#define ERROR_CONNECT_ALREADY_CONNECTED -302
#define ERROR_CONNECT_LLT_NUMBER_ALREADY_USED -303
#define ERROR_CONNECT_INVALID_DEVICE_ID -305

#define ERROR_PARTPROFILE_NO_PART_PROF -350
#define ERROR_PARTPROFILE_TOO_MUCH_BYTES -351
#define ERROR_PARTPROFILE_TOO_MUCH_POINTS -352
#define ERROR_PARTPROFILE_NO_POINT_COUNT -353
#define ERROR_PARTPROFILE_NOT_MOD_UNITSIZE_POINT -354
#define ERROR_PARTPROFILE_NOT_MOD_UNITSIZE_DATA -355

#define ERROR_TRANSERRORVALUE_WRONG_ERROR_VALUE -450
#define ERROR_TRANSERRORVALUE_BUFFER_SIZE_TOO_LOW -451

#define ERROR_READWRITECONFIG_CANT_CREATE_FILE -500
#define ERROR_READWRITECONFIG_CANT_OPEN_FILE -501
#define ERROR_READWRITECONFIG_QUEUE_TO_SMALL -502
#define ERROR_READWRITECONFIG_FILE_EMPTY -503
#define ERROR_READWRITECONFIG_UNKNOWN_FILE -504

#define ERROR_TRANSMISSION_CANCEL_NO_CAM -888
#define ERROR_DEVPROP_NOT_AVAILABLE -999

#define ERROR_GENERAL_NOT_CONNECTED -1001
#define ERROR_GENERAL_DEVICE_BUSY -1002
#define ERROR_GENERAL_WHILE_LOAD_PROFILE_OR_GET_PROFILES -1003
#define ERROR_GENERAL_WHILE_GET_PROFILES -1004
#define ERROR_GENERAL_GET_SET_ADDRESS -1005
#define ERROR_GENERAL_POINTER_MISSING -1006
#define ERROR_GENERAL_WHILE_SAVE_PROFILES -1007
#define ERROR_GENERAL_SECOND_CONNECTION_TO_LLT -1008
#define ERROR_TRANSMISSION_CANCEL_TRANSMISSION_ACTIVE -1009
#define ERROR_TRANSMISSION_CANCEL_NO_TRANSMISSION_ACTIVE -1010
#define ERROR_GENERAL_VALUE_NOT_ALLOWED -1011

#define ERROR_DEVPROP_NOT_FOUND -1300
#define ERROR_DEVPROP_DECODE -1301
#define ERROR_DEVPROP_DEPRECATED -1302
#define ERROR_DEVPROP_READ_FAILURE -1303
#define ERROR_DEVPROP_WRONG_FILE_FORMAT -1304
#define ERROR_DEVPROP_WRONG_CAMERA -1305

/***
 structs
***/

// device data read from properties file
typedef struct MEDeviceData {
    int device_series;
    double scaling;
    double offset;
    int max_packet_size;
    int max_frequency;
    int post_proc;
    double min_x_display;
    double max_x_display;
    double min_y_display;
    double max_y_display;
    int rotate_image;
    double min_width;
} MEDeviceData;

// partial profile size
typedef struct TPartialProfile {
    unsigned int nStartPoint;
    unsigned int nStartPointData;
    unsigned int nPointCount;
    unsigned int nPointDataWidth;
} TPartialProfile;

typedef struct EHANDLE EHANDLE;

typedef struct LLT LLT;

typedef enum TTransferProfileType {
    NORMAL_TRANSFER = 0,
    NORMAL_CONTAINER_MODE = 2,
    NONE_TRANSFER = 4,
} TTransferProfileType;

typedef enum TStreamPriorityState {
    PRIO_NOT_SET = 0,
    PRIO_SET_SUCCESS = 1,
    PRIO_SET_NICE_FAILED = 2,
    PRIO_SET_RT_FAILED = 3,
    PRIO_SET_FAILED = 4,
} TStreamPriorityState;

typedef enum TProfileConfig {
    NONE = 0,
    PROFILE = 1,
    PURE_PROFILE = 2,
    QUARTER_PROFILE = 3,
    // 4 reserved for CSV
    PARTIAL_PROFILE = 5,
    CONTAINER = 6,
    VIDEO_IMAGE = 7,
} TProfileConfig;

// specify scanner type
// if programming language don't support enums, use signed int
typedef enum TScannerType {
    StandardType = -1, // can't decode scanCONTROL

    scanCONTROL27xx_25 = 1000,
    scanCONTROL27xx_100 = 1001,
    scanCONTROL27xx_50 = 1002,
    scanCONTROL27xx_xxx = 1999,

    scanCONTROL26xx_25 = 2000,
    scanCONTROL26xx_100 = 2001,
    scanCONTROL26xx_50 = 2002,
    scanCONTROL26xx_10 = 2003,
    scanCONTROL26xx_xxx = 2999,

    scanCONTROL29xx_25 = 3000,
    scanCONTROL29xx_100 = 3001,
    scanCONTROL29xx_50 = 3002,
    scanCONTROL29xx_10 = 3003,
    scanCONTROL29xx_xxx = 3999,
} TScannerType;

#endif // LLTDATATYPES_H
